### ISSUE TITLE
how to run this project

### ISSUE THREAD

**Issue by shiro-siben** [RPCheung/shadowsockets-core#1]
i do not know run this project on windows,  can you please tell ?  thank you very much

**Comment by RPCheung** [comment]
Temporarily not running on Windows

**Comment by RPCheung** [comment]
> Temporarily not running on Windows
Temporarily not running on Windows

**Comment by CC-Cheunggg** [comment]
> i do not know run this project on windows, can you please tell ? thank you very much

Temporarily not running on Windows
