### ISSUE TITLE
config.xml配置参数

### ISSUE THREAD

**Issue by maomige** [RPCheung/shadowsockets-core#2]
兄die，config.xml的详细配置说明给一下呗
```
<?xml version="1.0" encoding="UTF-8" ?>
<config>
    <ipAddr>服务器IP？</ipAddr>
    <localIpAddr>127.0.0.1本机监听IP</localIpAddr>
    <track>true</track>
    <serverPort>1080服务器端口？</serverPort>
    <method>aes-256-cfb</method>
    <password>xxxxx</password>
</config>
```
请问本地监听端口在哪里配置？

SSR的协议类型在哪里配置还是不支持？也就是类似auth_sha1_v4,  auth_aes128_md5这种
协议参数呢，是否支持？
混淆方式，和混淆参数是否支持？

挺好的项目，希望完善文档，先赞为敬。

**Comment by maomige** [comment]
```
2019-07-10 17:20:13 - Unable to load the library 'netty_transport_native_epoll_x86_64', trying other loading mechanism.
java.lang.UnsatisfiedLinkError: no netty_transport_native_epoll_x86_64 in java.library.path
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1867) ~[?:1.8.0_211]
	at java.lang.Runtime.loadLibrary0(Runtime.java:870) ~[?:1.8.0_211]
	at java.lang.System.loadLibrary(System.java:1122) ~[?:1.8.0_211]
	at io.netty.util.internal.NativeLibraryUtil.loadLibrary(NativeLibraryUtil.java:38) ~[netty-all-4.1.33.Final.jar:4.1.33.Final]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_211]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_211]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_211]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_211]
	at io.netty.util.internal.NativeLibraryLoader$1.run(NativeLibraryLoader.java:336) ~[netty-all-4.1.33.Final.jar:4.1.33.Final]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_211]
	at io.netty.util.internal.NativeLibraryLoader.loadLibraryByHelper(NativeLibraryLoader.java:328) ~[netty-all-4.1.33.Final.jar:4.1.33.Final]
	at io.netty.util.internal.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:306) [netty-all-4.1.33.Final.jar:4.1.33.Final]
	at io.netty.util.internal.NativeLibraryLoader.load(NativeLibraryLoader.java:136) [netty-all-4.1.33.Final.jar:4.1.33.Final]
	at io.netty.channel.epoll.Native.loadNativeLibrary(Native.java:198) [netty-all-4.1.33.Final.jar:4.1.33.Final]
	at io.netty.channel.epoll.Native.<clinit>(Native.java:61) [netty-all-4.1.33.Final.jar:4.1.33.Final]
	at io.netty.channel.epoll.Epoll.<clinit>(Epoll.java
。。。
	at com.cheung.shadowsockets.common.CommonResourcesConfig.internetEventLoopGroup(CommonResourcesConfig.java:69) [shadowsockets-core-1.5.0.Final.jar:?]
	at com.cheung.shadowsockets.common.CommonResourcesConfig$$EnhancerBySpringCGLIB$$2f49233d.CGLIB$internetEventLoopGroup$4(<generated>) [shadowsockets-core-1.5.0.Final.jar:?]
	at com.cheung.shadowsockets.common.CommonResourcesConfig$$EnhancerBySpringCGLIB$$2f49233d$$FastClassBySpringCGLIB$$3d43c7aa.invoke(<generated>) [shadowsockets-core-1.5.0.Final.jar:?]
	

```

```
2019-07-10 17:20:13 - Unable to load the library 'netty_transport_native_epoll_x86_64', trying other loading mechanism.
java.lang.UnsatisfiedLinkError: no netty_transport_native_epoll_x86_64 in java.library.path
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1867) ~[?:1.8.0_211]
	at java.lang.Runtime.loadLibrary0(Runtime.java:870) ~[?:1.8.0_211]
	at java.lang.System.loadLibrary(System.java:1122) ~[?:1.8.0_211]
	at io.netty.util.internal.NativeLibraryUtil.loadLibrary(NativeLibraryUtil.java:38) ~[netty-all-4.1.33.Final.jar:4.1.33.Final]
。。。
2019-07-10 17:20:13 - start error
io.netty.channel.unix.Errors$NativeIoException: bind(..) failed: 无法指定被请求的地址
	at io.netty.channel.unix.Errors.newIOException(Errors.java:122) ~[netty-all-4.1.33.Final.jar:4.1.33.Final]
	at io.netty.channel.unix.Socket.bind(Socket.java:287) ~[netty-all-4.1.33.Final.jar:4.1.33.Final]
	at io.netty.channel.epoll.AbstractEpollChannel.doBind(AbstractEpollChannel.java:684) ~[netty-all-4.1.33.Final.jar:4.1.33.Final]
	at io.netty.channel.epoll.EpollServerSocketChannel.doBind(EpollServerSocketChannel.java:70) ~[netty-all-4.1.33.Final.jar:4.1.33.Final]
	at io.netty.channel.AbstractChannel$AbstractUnsafe.bind(AbstractChannel.java:562) ~[netty-all-4.1.33.Final.jar:4.1.33.Final]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.bind(DefaultChannelPipeline.java:1332) ~[netty-all-4.1.33.Final.jar:4.1.33.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeBind(AbstractChannelHandlerContext.java:501) ~[netty-all-4.1.33.Final.jar:4.1.33.Final]
	at io.netty.channel.AbstractChannelHandlerContext.bind(AbstractChannelHandlerContext.java:486) ~[netty-all-4.1.33.Final.jar:4.1.33.Final]
	at io.netty.channel.DefaultChannelPipeline.bind(DefaultChannelPipeline.java:984) ~[netty-all-4.1.33.Final.jar:4.1.33.Final]
	at io.netty.channel.AbstractChannel.bind(AbstractChannel.java:258) ~[netty-all-4.1.33.Final.jar:4.1.33.Final]
	at io.netty.bootstrap.AbstractBootstrap$2.run(AbstractBootstrap.java:366) ~[netty-all-4.1.33.Final.jar:4.1.33.Final]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163) ~[netty-all-4.1.33.Final.jar:4.1.33.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404) ~[netty-all-4.1.33.Final.jar:4.1.33.Final]
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:333) ~[netty-all-4.1.33.Final.jar:4.1.33.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:905) ~[netty-all-4.1.33.Final.jar:4.1.33.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-all-4.1.33.Final.jar:4.1.33.Final]
	at java.lang.Thread.run(Thread.java:748) ~[?:1.8.0_211]
2019-07-10 17:20:20 - Stop Server!
2019-07-10 17:20:20 - current server pid: 11090
2019-07-10 17:20:20 - default Configuration : port: 8388 , method: aes-256-cfb , passwo
```

另外启动报错，帮忙看下，谢谢。

jdk1.8.0_211 、ubuntu18

**Comment by RPCheung** [comment]
![image](https://user-images.githubusercontent.com/18390076/61234408-94b5f900-a765-11e9-9873-eac99d71468c.png)
参考配置一下 有问题再反馈

**Comment by RPCheung** [comment]
ava.lang.UnsatisfiedLinkError: no netty_transport_native_epoll_x86_64 in java.library.path
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1867) ~[?:1.8.0_211]
	at java.lang.Runtime.loadLibrary0(Runtime.java:870) ~[?:1.8.0_211]
	at java.lang.System.loadLibrary(System.java:1122) ~[?:1.8.0_211]
	at io.netty.util.internal.NativeLibraryUtil.loadLibrary(NativeLibraryUtil.java:38) ~[netty-all-4.1.33.Final.jar:4.1.33.Final]
。。。

这个错是jni的报错 netty会自动生成改so包 不影响正常只用

**Comment by CC-Cheunggg** [comment]
> 兄die，config.xml的详细配置说明给一下呗
> 
> ```
> <?xml version="1.0" encoding="UTF-8" ?>
> <config>
>     <ipAddr>服务器IP？</ipAddr>
>     <localIpAddr>127.0.0.1本机监听IP</localIpAddr>
>     <track>true</track>
>     <serverPort>1080服务器端口？</serverPort>
>     <method>aes-256-cfb</method>
>     <password>xxxxx</password>
> </config>
> ```
> 
> 请问本地监听端口在哪里配置？
> 
> SSR的协议类型在哪里配置还是不支持？也就是类似auth_sha1_v4, auth_aes128_md5这种
> 协议参数呢，是否支持？
> 混淆方式，和混淆参数是否支持？
> 
> 挺好的项目，希望完善文档，先赞为敬。

![image](https://user-images.githubusercontent.com/18390076/61235449-26bf0100-a768-11e9-9a50-596e7b85256f.png)
本项目只实现SS，不实现SSR，精力有限，敬请谅解

**Comment by RPCheung** [comment]
> ```
> 2019-07-10 17:20:13 - Unable to load the library 'netty_transport_native_epoll_x86_64', trying other loading mechanism.
> java.lang.UnsatisfiedLinkError: no netty_transport_native_epoll_x86_64 in java.library.path
> 	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1867) ~[?:1.8.0_211]
> 	at java.lang.Runtime.loadLibrary0(Runtime.java:870) ~[?:1.8.0_211]
> 	at java.lang.System.loadLibrary(System.java:1122) ~[?:1.8.0_211]
> 	at io.netty.util.internal.NativeLibraryUtil.loadLibrary(NativeLibraryUtil.java:38) ~[netty-all-4.1.33.Final.jar:4.1.33.Final]
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_211]
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_211]
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_211]
> 	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_211]
> 	at io.netty.util.internal.NativeLibraryLoader$1.run(NativeLibraryLoader.java:336) ~[netty-all-4.1.33.Final.jar:4.1.33.Final]
> 	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_211]
> 	at io.netty.util.internal.NativeLibraryLoader.loadLibraryByHelper(NativeLibraryLoader.java:328) ~[netty-all-4.1.33.Final.jar:4.1.33.Final]
> 	at io.netty.util.internal.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:306) [netty-all-4.1.33.Final.jar:4.1.33.Final]
> 	at io.netty.util.internal.NativeLibraryLoader.load(NativeLibraryLoader.java:136) [netty-all-4.1.33.Final.jar:4.1.33.Final]
> 	at io.netty.channel.epoll.Native.loadNativeLibrary(Native.java:198) [netty-all-4.1.33.Final.jar:4.1.33.Final]
> 	at io.netty.channel.epoll.Native.<clinit>(Native.java:61) [netty-all-4.1.33.Final.jar:4.1.33.Final]
> 	at io.netty.channel.epoll.Epoll.<clinit>(Epoll.java
> 。。。
> 	at com.cheung.shadowsockets.common.CommonResourcesConfig.internetEventLoopGroup(CommonResourcesConfig.java:69) [shadowsockets-core-1.5.0.Final.jar:?]
> 	at com.cheung.shadowsockets.common.CommonResourcesConfig$$EnhancerBySpringCGLIB$$2f49233d.CGLIB$internetEventLoopGroup$4(<generated>) [shadowsockets-core-1.5.0.Final.jar:?]
> 	at com.cheung.shadowsockets.common.CommonResourcesConfig$$EnhancerBySpringCGLIB$$2f49233d$$FastClassBySpringCGLIB$$3d43c7aa.invoke(<generated>) [shadowsockets-core-1.5.0.Final.jar:?]
> 	
> ```
> 
> ```
> 2019-07-10 17:20:13 - Unable to load the library 'netty_transport_native_epoll_x86_64', trying other loading mechanism.
> java.lang.UnsatisfiedLinkError: no netty_transport_native_epoll_x86_64 in java.library.path
> 	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1867) ~[?:1.8.0_211]
> 	at java.lang.Runtime.loadLibrary0(Runtime.java:870) ~[?:1.8.0_211]
> 	at java.lang.System.loadLibrary(System.java:1122) ~[?:1.8.0_211]
> 	at io.netty.util.internal.NativeLibraryUtil.loadLibrary(NativeLibraryUtil.java:38) ~[netty-all-4.1.33.Final.jar:4.1.33.Final]
> 。。。
> 2019-07-10 17:20:13 - start error
> io.netty.channel.unix.Errors$NativeIoException: bind(..) failed: 无法指定被请求的地址
> 	at io.netty.channel.unix.Errors.newIOException(Errors.java:122) ~[netty-all-4.1.33.Final.jar:4.1.33.Final]
> 	at io.netty.channel.unix.Socket.bind(Socket.java:287) ~[netty-all-4.1.33.Final.jar:4.1.33.Final]
> 	at io.netty.channel.epoll.AbstractEpollChannel.doBind(AbstractEpollChannel.java:684) ~[netty-all-4.1.33.Final.jar:4.1.33.Final]
> 	at io.netty.channel.epoll.EpollServerSocketChannel.doBind(EpollServerSocketChannel.java:70) ~[netty-all-4.1.33.Final.jar:4.1.33.Final]
> 	at io.netty.channel.AbstractChannel$AbstractUnsafe.bind(AbstractChannel.java:562) ~[netty-all-4.1.33.Final.jar:4.1.33.Final]
> 	at io.netty.channel.DefaultChannelPipeline$HeadContext.bind(DefaultChannelPipeline.java:1332) ~[netty-all-4.1.33.Final.jar:4.1.33.Final]
> 	at io.netty.channel.AbstractChannelHandlerContext.invokeBind(AbstractChannelHandlerContext.java:501) ~[netty-all-4.1.33.Final.jar:4.1.33.Final]
> 	at io.netty.channel.AbstractChannelHandlerContext.bind(AbstractChannelHandlerContext.java:486) ~[netty-all-4.1.33.Final.jar:4.1.33.Final]
> 	at io.netty.channel.DefaultChannelPipeline.bind(DefaultChannelPipeline.java:984) ~[netty-all-4.1.33.Final.jar:4.1.33.Final]
> 	at io.netty.channel.AbstractChannel.bind(AbstractChannel.java:258) ~[netty-all-4.1.33.Final.jar:4.1.33.Final]
> 	at io.netty.bootstrap.AbstractBootstrap$2.run(AbstractBootstrap.java:366) ~[netty-all-4.1.33.Final.jar:4.1.33.Final]
> 	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163) ~[netty-all-4.1.33.Final.jar:4.1.33.Final]
> 	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404) ~[netty-all-4.1.33.Final.jar:4.1.33.Final]
> 	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:333) ~[netty-all-4.1.33.Final.jar:4.1.33.Final]
> 	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:905) ~[netty-all-4.1.33.Final.jar:4.1.33.Final]
> 	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-all-4.1.33.Final.jar:4.1.33.Final]
> 	at java.lang.Thread.run(Thread.java:748) ~[?:1.8.0_211]
> 2019-07-10 17:20:20 - Stop Server!
> 2019-07-10 17:20:20 - current server pid: 11090
> 2019-07-10 17:20:20 - default Configuration : port: 8388 , method: aes-256-cfb , passwo
> ```
> 
> 另外启动报错，帮忙看下，谢谢。
> 
> jdk1.8.0_211 、ubuntu18

这个错是jni的报错 netty会自动生成改so包 不影响正常只用

**Comment by RPCheung** [comment]
> ```
> 2019-07-10 17:20:13 - Unable to load the library 'netty_transport_native_epoll_x86_64', trying other loading mechanism.
> java.lang.UnsatisfiedLinkError: no netty_transport_native_epoll_x86_64 in java.library.path
> 	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1867) ~[?:1.8.0_211]
> 	at java.lang.Runtime.loadLibrary0(Runtime.java:870) ~[?:1.8.0_211]
> 	at java.lang.System.loadLibrary(System.java:1122) ~[?:1.8.0_211]
> 	at io.netty.util.internal.NativeLibraryUtil.loadLibrary(NativeLibraryUtil.java:38) ~[netty-all-4.1.33.Final.jar:4.1.33.Final]
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_211]
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_211]
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_211]
> 	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_211]
> 	at io.netty.util.internal.NativeLibraryLoader$1.run(NativeLibraryLoader.java:336) ~[netty-all-4.1.33.Final.jar:4.1.33.Final]
> 	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_211]
> 	at io.netty.util.internal.NativeLibraryLoader.loadLibraryByHelper(NativeLibraryLoader.java:328) ~[netty-all-4.1.33.Final.jar:4.1.33.Final]
> 	at io.netty.util.internal.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:306) [netty-all-4.1.33.Final.jar:4.1.33.Final]
> 	at io.netty.util.internal.NativeLibraryLoader.load(NativeLibraryLoader.java:136) [netty-all-4.1.33.Final.jar:4.1.33.Final]
> 	at io.netty.channel.epoll.Native.loadNativeLibrary(Native.java:198) [netty-all-4.1.33.Final.jar:4.1.33.Final]
> 	at io.netty.channel.epoll.Native.<clinit>(Native.java:61) [netty-all-4.1.33.Final.jar:4.1.33.Final]
> 	at io.netty.channel.epoll.Epoll.<clinit>(Epoll.java
> 。。。
> 	at com.cheung.shadowsockets.common.CommonResourcesConfig.internetEventLoopGroup(CommonResourcesConfig.java:69) [shadowsockets-core-1.5.0.Final.jar:?]
> 	at com.cheung.shadowsockets.common.CommonResourcesConfig$$EnhancerBySpringCGLIB$$2f49233d.CGLIB$internetEventLoopGroup$4(<generated>) [shadowsockets-core-1.5.0.Final.jar:?]
> 	at com.cheung.shadowsockets.common.CommonResourcesConfig$$EnhancerBySpringCGLIB$$2f49233d$$FastClassBySpringCGLIB$$3d43c7aa.invoke(<generated>) [shadowsockets-core-1.5.0.Final.jar:?]
> 	
> ```
> 
> ```
> 2019-07-10 17:20:13 - Unable to load the library 'netty_transport_native_epoll_x86_64', trying other loading mechanism.
> java.lang.UnsatisfiedLinkError: no netty_transport_native_epoll_x86_64 in java.library.path
> 	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1867) ~[?:1.8.0_211]
> 	at java.lang.Runtime.loadLibrary0(Runtime.java:870) ~[?:1.8.0_211]
> 	at java.lang.System.loadLibrary(System.java:1122) ~[?:1.8.0_211]
> 	at io.netty.util.internal.NativeLibraryUtil.loadLibrary(NativeLibraryUtil.java:38) ~[netty-all-4.1.33.Final.jar:4.1.33.Final]
> 。。。
> 2019-07-10 17:20:13 - start error
> io.netty.channel.unix.Errors$NativeIoException: bind(..) failed: 无法指定被请求的地址
> 	at io.netty.channel.unix.Errors.newIOException(Errors.java:122) ~[netty-all-4.1.33.Final.jar:4.1.33.Final]
> 	at io.netty.channel.unix.Socket.bind(Socket.java:287) ~[netty-all-4.1.33.Final.jar:4.1.33.Final]
> 	at io.netty.channel.epoll.AbstractEpollChannel.doBind(AbstractEpollChannel.java:684) ~[netty-all-4.1.33.Final.jar:4.1.33.Final]
> 	at io.netty.channel.epoll.EpollServerSocketChannel.doBind(EpollServerSocketChannel.java:70) ~[netty-all-4.1.33.Final.jar:4.1.33.Final]
> 	at io.netty.channel.AbstractChannel$AbstractUnsafe.bind(AbstractChannel.java:562) ~[netty-all-4.1.33.Final.jar:4.1.33.Final]
> 	at io.netty.channel.DefaultChannelPipeline$HeadContext.bind(DefaultChannelPipeline.java:1332) ~[netty-all-4.1.33.Final.jar:4.1.33.Final]
> 	at io.netty.channel.AbstractChannelHandlerContext.invokeBind(AbstractChannelHandlerContext.java:501) ~[netty-all-4.1.33.Final.jar:4.1.33.Final]
> 	at io.netty.channel.AbstractChannelHandlerContext.bind(AbstractChannelHandlerContext.java:486) ~[netty-all-4.1.33.Final.jar:4.1.33.Final]
> 	at io.netty.channel.DefaultChannelPipeline.bind(DefaultChannelPipeline.java:984) ~[netty-all-4.1.33.Final.jar:4.1.33.Final]
> 	at io.netty.channel.AbstractChannel.bind(AbstractChannel.java:258) ~[netty-all-4.1.33.Final.jar:4.1.33.Final]
> 	at io.netty.bootstrap.AbstractBootstrap$2.run(AbstractBootstrap.java:366) ~[netty-all-4.1.33.Final.jar:4.1.33.Final]
> 	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163) ~[netty-all-4.1.33.Final.jar:4.1.33.Final]
> 	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404) ~[netty-all-4.1.33.Final.jar:4.1.33.Final]
> 	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:333) ~[netty-all-4.1.33.Final.jar:4.1.33.Final]
> 	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:905) ~[netty-all-4.1.33.Final.jar:4.1.33.Final]
> 	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-all-4.1.33.Final.jar:4.1.33.Final]
> 	at java.lang.Thread.run(Thread.java:748) ~[?:1.8.0_211]
> 2019-07-10 17:20:20 - Stop Server!
> 2019-07-10 17:20:20 - current server pid: 11090
> 2019-07-10 17:20:20 - default Configuration : port: 8388 , method: aes-256-cfb , passwo
> ```
> 
> 另外启动报错，帮忙看下，谢谢。
> 
> jdk1.8.0_211 、ubuntu18

这个错是jni的报错 netty会自动生成改so包 不影响正常只用

**Comment by CC-Cheunggg** [comment]
> ```
> 2019-07-10 17:20:13 - Unable to load the library 'netty_transport_native_epoll_x86_64', trying other loading mechanism.
> java.lang.UnsatisfiedLinkError: no netty_transport_native_epoll_x86_64 in java.library.path
> 	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1867) ~[?:1.8.0_211]
> 	at java.lang.Runtime.loadLibrary0(Runtime.java:870) ~[?:1.8.0_211]
> 	at java.lang.System.loadLibrary(System.java:1122) ~[?:1.8.0_211]
> 	at io.netty.util.internal.NativeLibraryUtil.loadLibrary(NativeLibraryUtil.java:38) ~[netty-all-4.1.33.Final.jar:4.1.33.Final]
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_211]
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_211]
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_211]
> 	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_211]
> 	at io.netty.util.internal.NativeLibraryLoader$1.run(NativeLibraryLoader.java:336) ~[netty-all-4.1.33.Final.jar:4.1.33.Final]
> 	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_211]
> 	at io.netty.util.internal.NativeLibraryLoader.loadLibraryByHelper(NativeLibraryLoader.java:328) ~[netty-all-4.1.33.Final.jar:4.1.33.Final]
> 	at io.netty.util.internal.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:306) [netty-all-4.1.33.Final.jar:4.1.33.Final]
> 	at io.netty.util.internal.NativeLibraryLoader.load(NativeLibraryLoader.java:136) [netty-all-4.1.33.Final.jar:4.1.33.Final]
> 	at io.netty.channel.epoll.Native.loadNativeLibrary(Native.java:198) [netty-all-4.1.33.Final.jar:4.1.33.Final]
> 	at io.netty.channel.epoll.Native.<clinit>(Native.java:61) [netty-all-4.1.33.Final.jar:4.1.33.Final]
> 	at io.netty.channel.epoll.Epoll.<clinit>(Epoll.java
> 。。。
> 	at com.cheung.shadowsockets.common.CommonResourcesConfig.internetEventLoopGroup(CommonResourcesConfig.java:69) [shadowsockets-core-1.5.0.Final.jar:?]
> 	at com.cheung.shadowsockets.common.CommonResourcesConfig$$EnhancerBySpringCGLIB$$2f49233d.CGLIB$internetEventLoopGroup$4(<generated>) [shadowsockets-core-1.5.0.Final.jar:?]
> 	at com.cheung.shadowsockets.common.CommonResourcesConfig$$EnhancerBySpringCGLIB$$2f49233d$$FastClassBySpringCGLIB$$3d43c7aa.invoke(<generated>) [shadowsockets-core-1.5.0.Final.jar:?]
> 	
> ```
> 
> ```
> 2019-07-10 17:20:13 - Unable to load the library 'netty_transport_native_epoll_x86_64', trying other loading mechanism.
> java.lang.UnsatisfiedLinkError: no netty_transport_native_epoll_x86_64 in java.library.path
> 	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1867) ~[?:1.8.0_211]
> 	at java.lang.Runtime.loadLibrary0(Runtime.java:870) ~[?:1.8.0_211]
> 	at java.lang.System.loadLibrary(System.java:1122) ~[?:1.8.0_211]
> 	at io.netty.util.internal.NativeLibraryUtil.loadLibrary(NativeLibraryUtil.java:38) ~[netty-all-4.1.33.Final.jar:4.1.33.Final]
> 。。。
> 2019-07-10 17:20:13 - start error
> io.netty.channel.unix.Errors$NativeIoException: bind(..) failed: 无法指定被请求的地址
> 	at io.netty.channel.unix.Errors.newIOException(Errors.java:122) ~[netty-all-4.1.33.Final.jar:4.1.33.Final]
> 	at io.netty.channel.unix.Socket.bind(Socket.java:287) ~[netty-all-4.1.33.Final.jar:4.1.33.Final]
> 	at io.netty.channel.epoll.AbstractEpollChannel.doBind(AbstractEpollChannel.java:684) ~[netty-all-4.1.33.Final.jar:4.1.33.Final]
> 	at io.netty.channel.epoll.EpollServerSocketChannel.doBind(EpollServerSocketChannel.java:70) ~[netty-all-4.1.33.Final.jar:4.1.33.Final]
> 	at io.netty.channel.AbstractChannel$AbstractUnsafe.bind(AbstractChannel.java:562) ~[netty-all-4.1.33.Final.jar:4.1.33.Final]
> 	at io.netty.channel.DefaultChannelPipeline$HeadContext.bind(DefaultChannelPipeline.java:1332) ~[netty-all-4.1.33.Final.jar:4.1.33.Final]
> 	at io.netty.channel.AbstractChannelHandlerContext.invokeBind(AbstractChannelHandlerContext.java:501) ~[netty-all-4.1.33.Final.jar:4.1.33.Final]
> 	at io.netty.channel.AbstractChannelHandlerContext.bind(AbstractChannelHandlerContext.java:486) ~[netty-all-4.1.33.Final.jar:4.1.33.Final]
> 	at io.netty.channel.DefaultChannelPipeline.bind(DefaultChannelPipeline.java:984) ~[netty-all-4.1.33.Final.jar:4.1.33.Final]
> 	at io.netty.channel.AbstractChannel.bind(AbstractChannel.java:258) ~[netty-all-4.1.33.Final.jar:4.1.33.Final]
> 	at io.netty.bootstrap.AbstractBootstrap$2.run(AbstractBootstrap.java:366) ~[netty-all-4.1.33.Final.jar:4.1.33.Final]
> 	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163) ~[netty-all-4.1.33.Final.jar:4.1.33.Final]
> 	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404) ~[netty-all-4.1.33.Final.jar:4.1.33.Final]
> 	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:333) ~[netty-all-4.1.33.Final.jar:4.1.33.Final]
> 	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:905) ~[netty-all-4.1.33.Final.jar:4.1.33.Final]
> 	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-all-4.1.33.Final.jar:4.1.33.Final]
> 	at java.lang.Thread.run(Thread.java:748) ~[?:1.8.0_211]
> 2019-07-10 17:20:20 - Stop Server!
> 2019-07-10 17:20:20 - current server pid: 11090
> 2019-07-10 17:20:20 - default Configuration : port: 8388 , method: aes-256-cfb , passwo
> ```
> 
> 另外启动报错，帮忙看下，谢谢。
> 
> jdk1.8.0_211 、ubuntu18

这个错是jni的报错 netty会自动生成改so包 不影响正常只用
